spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: Passw0rd@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      # Thread Pool
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 25
      org.quartz.threadPool.threadPriority: 5
      # Job Store
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartz
      # Data source
      org.quartz.dataSource.quartz.driver: com.mysql.jdbc.Driver
      org.quartz.dataSource.quartz.URL: jdbc:mysql://localhost:3306/quartz
      org.quartz.dataSource.quartz.user: root
      org.quartz.dataSource.quartz.password: Passw0rd@
      org.quartz.dataSource.quartz.provider: hikaricp
