spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: Passw0rd@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
